### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SeekMoment** [mehrdadep/deep-learning-nids#2]
Hello, when i am trying to use the CICIDS dataset, i have this error:
Traceback (most recent call last):
  File "run.py", line 63, in <module>
    Runner.run(run_type, dataset, model_type, epochs_num)
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/models/runner.py", line 20, in run
    x_train, y_train, x_test, y_test = Processor.get_data(
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/services/process.py", line 891, in get_data
    return cls.cicids_data_multiclass()
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/services/process.py", line 669, in cicids_data_multiclass
    cls.cicids_process_multiclass()
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/services/process.py", line 539, in cicids_process_multiclass
    train_data_6 = cls.read_file_lines('cicids',
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/services/process.py", line 26, in read_file_lines
    return content.readlines()
  File "/home/maxim/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 6014: invalid start byte

**Comment by mehrdadep** [comment]
Unfortunately, this error is not reproducible on my system. Here is the output for `multiclass` for `cicids` dataset with `lstm` model

```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
simple_rnn_1 (SimpleRNN)     (None, 1, 120)            23880     
_________________________________________________________________
dropout_1 (Dropout)          (None, 1, 120)            0         
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (None, 1, 120)            28920     
_________________________________________________________________
dropout_2 (Dropout)          (None, 1, 120)            0         
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 120)               28920     
_________________________________________________________________
dropout_3 (Dropout)          (None, 120)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 484       
_________________________________________________________________
activation_1 (Activation)    (None, 4)                 0         
=================================================================
Total params: 82,204
Trainable params: 82,204
Non-trainable params: 0
_________________________________________________________________
Train on 216451 samples, validate on 72151 samples
Epoch 1/1
216451/216451 [==============================] - 28s 128us/step - loss: 0.0030 - accuracy: 0.9996 - val_loss: 8.8868e-04 - val_accuracy: 0.9999
--- 31.331366300582886 seconds ---
72151/72151 [==============================] - 2s 34us/step

Loss: 0.00, Accuracy: 99.99%

Anomaly in Test:  [72143     0     0     8]

Anomaly in Prediction:  1
```

Try to change [this line](https://github.com/mehrdadep/deep-learning-nids/blob/master/services/process.py#L25) with different encodings and see anything changes or not. For example

```
with open(filepath, 'r', encoding='utf-16') as content:
```

or

```
with open(filepath, 'r', encoding='ISO-8859-1') as content:
```

See [here](https://stackoverflow.com/questions/21504319/python-3-csv-file-giving-unicodedecodeerror-utf-8-codec-cant-decode-byte-err) for more info

**Comment by SeekMoment** [comment]
Okay, I've fixed it, I've got a new problem:
Traceback (most recent call last):
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/run.py", line 60, in <module>
    Runner.run(run_type, dataset, model_type, epochs_num)
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/models/runner.py", line 22, in run
    dataset,
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/services/process.py", line 883, in get_data
    return cls.cicids_data_binary()
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/services/process.py", line 847, in cicids_data_binary
    cls.cicids_process_data_binary()
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/services/process.py", line 793, in cicids_process_data_binary
    for x in raw_train_data_features]
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/services/process.py", line 793, in <listcomp>
    for x in raw_train_data_features]
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/services/process.py", line 77, in numericalize_feature_cicids
    x) for x in feature]
  File "/home/maxim/PycharmProjects/deep-learning-nids-master1/services/process.py", line 77, in <listcomp>
    x) for x in feature]
ValueError: could not convert string to float: '172.16.0.1-192.168.10.50-35472-80-6'
